GitHub codespaces install script cleanup

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,172 +1,97 @@
 #!/bin/bash
-# Used to setup codespaces
-# It ain't pretty, but it's honest work
+# GitHub codespaces setup.
 
 exec > >(tee -i $HOME/dotfiles_install.log)
 exec 2>&1
 set -x
 
-un="$(uname)"
-case "${un}" in
-  Linux)
-    ostype=linux
-    homebrew_prefix_default=/home/linuxbrew/.linuxbrew
-    ;;
-  Darwin)
-    ostype=macos
-    if [[ "$(uname -m)" == "arm64" ]]
-    then
-      homebrew_prefix_default=/opt/homebrew
-    else
-      homebrew_prefix_default=/usr/local
+function link_files() {
+  # In some codespaces, there's no need to symlink dotfiles to $HOME
+  if [[ ! $(pwd) -ef $HOME ]]; then
+    mkdir -p ~/.config/
+    ln -s $(pwd)/.config/nvim ~/.config/
+    ln -s $(pwd)/.gitignore_global ~/.gitignore_global
+    ln -s $(pwd)/.git_template ~/.git_template
+    ln -s $(pwd)/.tmux.conf ~/.tmux.conf
+    ln -s $(pwd)/bin ~/.bin
+    ln -s $(pwd)/.config/fish ~/.config/
+    ln -s $(pwd)/script/git-hooks/pre-push .git/hooks/pre-push
+
+    rm -f ~/.gitconfig
+    ln -s $(pwd)/.gitconfig ~/.gitconfig
+
+    if [ -d "/workspaces/github/bin" ]; then
+      sudo ln -s /workspaces/github/bin/rubocop /usr/local/bin/rubocop
+      sudo ln -s /workspaces/github/bin/srb /usr/local/bin/srb
+      sudo ln -s /workspaces/github/bin/solargraph /usr/local/bin/solargraph
     fi
-esac
+  fi
+}
 
-if [[ ! -d "${homebrew_prefix_default}" ]]; then
-  echo "Homebrew not found, installing..."
-  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-
-  if [[ "${un}" == "Linux" ]]; then
+brew_path=/home/linuxbrew/.linuxbrew # avoid brew command not found in codespaces
+function install_homebrew() {
+  if [[ ! -d "${brew_path}" ]]; then
+    echo "🍺 Homebrew not found, installing..."
+    export HOMEBREW_INSTALL_FROM_API=true # Don't fully clone homebrew. Provides a speed boost.
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
     test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
     test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
     test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bash_profile
     echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.profile
+  else
+    echo "🍺 Homebrew already installed, skipping..."
   fi
-fi
+}
 
-brew="$homebrew_prefix_default/bin/brew"
+function install_software() {
+  curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
+  sudo apt-get install -y nodejs
+  curl https://github.com/dandavison/delta/releases/download/0.13.0/git-delta_0.13.0_amd64.deb > ~/git-delta.deb
+  sudo dpkg -i ~/git-delta_0.13.0_amd64.deb
+  sudo npm install -g typescript-language-server typescript vscode-langservers-extracted eslint_d
+  sudo apt -o DPkg::Lock::Timeout=600 install build-essential python3-venv ruby-dev fzf bat exa jq ripgrep thefuck tmux libfuse2 fuse software-properties-common -y
+  install_homebrew
+  $brew_path/bin/brew install fish
+  if ! command -v nvim &> /dev/null; then
+    echo "neovim not found, installing..."
+    $brew_path/bin/brew install neovim
+  fi
+}
 
-$brew install fish
-$brew install neovim
-$brew install ripgrep
-$brew install tmux
-$brew install fzf
-$brew install --HEAD universal-ctags
+function setup_software() {
+  # Use remote-development-manager for copy/paste and open support
+  wget https://github.com/BlakeWilliams/remote-development-manager/releases/download/v0.0.3/rdm-linux-amd64
+  sudo mv rdm-linux-amd64 /usr/bin/rdm
+  chmod +x /usr/bin/rdm
+  gh config set browser "rdm open"
 
-# Use RDM for copy/paste and open support
-wget https://github.com/BlakeWilliams/remote-development-manager/releases/download/v0.0.3/rdm-linux-amd64
-sudo mv rdm-linux-amd64 /usr/bin/rdm
-chmod +x /usr/bin/rdm
+  # Install Neovim plugins
+  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
+    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
+  $brew_path/bin/nvim --headless +PlugInstall +qa
 
-gh config set browser "rdm open"
+  # Accept Copilot license
+  mkdir -p ~/.config/github-copilot
+  echo '{"luanzeba":{"version":"2021-10-14"}}' > ~/.config/github-copilot/terms.json
+  $brew_path/bin/nvim --headless +"Copilot setup" +qa
 
-# In some codespaces, there's no need to symlink dotfiles to $HOME
-if [[ ! $PWD -ef $HOME ]]; then
-  # Link dotfiles
-  mkdir -p $HOME/.config/nvim
-  mkdir -p $HOME/.config/fish
-  mkdir -p $HOME/.bin
-  mkdir -p $HOME/.config/github-copilot
-  mkdir $HOME/.git_template
+  # Initialize git fish plugin
+  echo "__git.init" | $brew_path/bin/fish
 
-  ln -svf $PWD/.config/nvim/* $HOME/.config/nvim/
-  ln -svf $PWD/.config/github-copilot/terms.json $HOME/.config/github-copilot/terms.json
-  ln -svf $PWD/.gitconfig $HOME/.gitconfig
-  ln -svf $PWD/.gitignore_global $HOME/.gitignore_global
-  ln -svf $PWD/.git_template/* $HOME/.git_template/
-  ln -svf $PWD/.tmux.conf $HOME/.tmux.conf
-  ln -svf $PWD/bin/* $HOME/.bin/
+  # Change default shell to fish
+  sudo chsh -s $brew_path/bin/fish "$(whoami)"
+}
 
-  ln -s $PWD/script/git-hooks/pre-push .git/hooks/pre-push
+echo '🔗 Linking files.'
+echo `date +"%Y-%m-%d %T"`
+link_files
 
-  ln -svf $PWD/.config/fish/* $HOME/.config/fish/
-  ln -svf $PWD/.config/fish/functions/* $HOME/.config/fish/functions/
-fi
+echo '💽 Installing software'
+echo `date +"%Y-%m-%d %T"`
+install_software
 
-# Install vim-plug
-sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
-  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
-
-# Install neovim plugins
-# and accept copilot terms (This assumes the terms are already stored in $HOME/.config/github-copilot/terms.json)
-homebrew_nvim_path="${homebrew_prefix_default}/bin/nvim"
-$homebrew_nvim_path --headless +PlugInstall +qa
-$homebrew_nvim_path --headless +"Copilot setup" +qa
-
-# Set fish as default shell
-homebrew_fish_path="${homebrew_prefix_default}/bin/fish"
-
-echo "curl -sL https://git.io/fisher | source && fisher update" | $homebrew_fish_path
-
-echo $homebrew_fish_path | sudo tee -a /etc/shells
-sudo chsh -s $homebrew_fish_path "$(whoami)"
-
-# else
-#   # The setup below breaks all of the time, remove ASAP
-
-#   # When setting up a codespace, we might run into an apt race condition
-#   # We need to make sure a different process doesn't have a lock before proceeding
-#   # When it does, the error will be one of 2:
-#   #   Could not get lock /var/lib/apt/lists/lock
-#   #   Could not get lock /var/lib/dpkg/lock-frontend
-#   function apt_with_lock_protection() {
-#     while sudo apt-get -y $1 2>&1 | tee -a ~/apt_log | grep -q "Could not get lock" ; do
-#       echo "Waiting for other apt-get instances to exit"
-#       sleep 1
-#     done
-#   }
-
-#   # Download fish shell
-#   debian_version=$(lsb_release -a 2>/dev/null | awk '/Release/ {print $2}')
-#   echo "deb http://download.opensuse.org/repositories/shells:/fish/Debian_$debian_version/ /" | sudo tee /etc/apt/sources.list.d/shells:fish.list
-#   curl -fsSL https://download.opensuse.org/repositories/shells:fish/Debian_$debian_version/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish.gpg > /dev/null
-
-#   # Clean up codespaces environment
-#   previous=$PWD
-#   cd $HOME
-
-#   rm ~/.zshrc
-#   mv ~/.gitconfig ~/.gitconfig.old
-
-#   apt_with_lock_protection "update"
-#   apt_with_lock_protection "install ripgrep tmux exuberant-ctags fzf"
-#   apt_with_lock_protection "remove fish fish-common"
-#   apt_with_lock_protection "install fish"
-
-#   # Use RDM for copy/paste and open support
-#   wget https://github.com/BlakeWilliams/remote-development-manager/releases/download/v0.0.3/rdm-linux-amd64
-#   sudo mv rdm-linux-amd64 /usr/bin/rdm
-#   chmod +x /usr/bin/rdm
-
-#   gh config set browser "rdm open"
-
-#   # Link dotfiles
-#   mkdir -p $HOME/.config/nvim
-#   mkdir -p $HOME/.config/fish
-#   mkdir -p $HOME/.config/bin
-#   mkdir -p $HOME/.config/github-copilot
-#   mkdir $HOME/.git_template
-
-#   ln -svf $PWD/.config/nvim/* $HOME/.config/nvim/
-#   ln -svf $PWD/.config/github-copilot/terms.json $HOME/.config/github-copilot/terms.json
-#   ln -svf $PWD/.gitconfig $HOME/.gitconfig
-#   ln -svf $PWD/.gitignore_global ~/.gitignore_global
-#   ln -svf $PWD/.git_template/* ~/.git_template/
-#   ln -svf $PWD/.tmux.conf ~/.tmux.conf
-#   ln -svf $PWD/bin/* /usr/local/bin/
-
-#   ln -s $PWD/script/git-hooks/pre-push .git/hooks/pre-push
-
-#   ln -svf $PWD/.config/fish/* $HOME/.config/fish/
-#   ln -svf $PWD/.config/fish/functions/* $HOME/.config/fish/functions/
-
-#   # Install latest neovim
-#   curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
-#   chmod u+x nvim.appimage
-#   ./nvim.appimage --appimage-extract
-#   ./squashfs-root/AppRun --version
-#   mv squashfs-root /
-#   ln -s /squashfs-root/AppRun /usr/bin/nvim
-#   cd $previous
-
-#   # Install vim-plug
-#   sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
-#     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
-
-#   # Install neovim plugins
-#   # and accept copilot terms (This assumes the terms are already stored in $HOME/.config/github-copilot/terms.json)
-#   nvim --headless +PlugInstall +"Copilot setup" +qa
-
-#   sudo chsh -s "$(which fish)" "$(whoami)"
-# fi
-
+echo '🧰 configure software'
+echo `date +"%Y-%m-%d %T"`
+setup_software
+echo '✅ Done!'
+echo `date +"%Y-%m-%d %T"`
