Install neovim from AppImage
Trying to install it through homebrew was failing in certain codespaces
complaining that it couldn't find the python dependency even though
python3 was already installed.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -43,6 +43,27 @@ function install_homebrew() {
   fi
 }
 
+function install_neovim() {
+  if ! command -v nvim &> /dev/null; then
+    previous=$(pwd)
+    echo "Neovim not found, installing..."
+    cd /usr/bin
+    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
+    chmod u+x nvim.appimage
+    if ./nvim.appimage --version >& /dev/null; then
+      sudo ln -s ./nvim.appimage nvim
+    else
+      ./nvim.appimage --appimage-extract
+      sudo mv squashfs-root /
+      sudo ln -s /squashfs-root/AppRun /usr/bin/nvim
+      rm nvim.appimage
+    fi
+    cd $previous
+  else
+    echo "Neovim already installed, skipping..."
+  fi
+}
+
 function install_software() {
   curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
   sudo apt-get install -y nodejs
@@ -52,10 +73,7 @@ function install_software() {
   sudo apt -o DPkg::Lock::Timeout=600 install build-essential python3-venv ruby-dev fzf bat exa jq ripgrep thefuck tmux libfuse2 fuse software-properties-common -y
   install_homebrew
   $brew_path/bin/brew install fish
-  if ! command -v nvim &> /dev/null; then
-    echo "neovim not found, installing..."
-    $brew_path/bin/brew install neovim
-  fi
+  install_neovim
 }
 
 function setup_software() {
